- name: Allow kube control traffic
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
    interface: enp7s0
    direction: in
    src: 10.240.0.0/24
  loop:
    - '6443'
    - 2379:2380
    - 10250:10252

- name: Allow traffic from flannel CIDR to kubeapi server
  community.general.ufw:
    rule: allow
    port: '6443'
    proto: tcp
    interface: cni0
    direction: in
    src: 10.244.0.0/16

- name: Allow flannel traffic between nodes
  community.general.ufw:
    rule: allow
    port: '8472'
    proto: udp
    interface: enp7s0
    direction: in
    src: 10.240.0.0/24
    dest: 10.240.0.0/24
